### PR TITLE
fix: ubuntu pipx installation by calling pip from python3

### LINKED ISSUE #68: pipx: command not found in v3 action
v3 action fails because pipx is not on PATH

``` yaml
name: Upload Python Package

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    env:
      POETRY_VERSION: 1.5.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache-dependency-path: "poetry.lock"
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
```

```
Run abatilo/actions-poetry@v3
Run pip install --user pipx
Collecting pipx
  Downloading pipx-1.4.3-py3-none-any.whl.metadata (17 kB)
Collecting argcomplete>=1.9.4 (from pipx)
  Downloading argcomplete-3.2.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging>=20 in /tmp/_tool/Python/3.10.13/x64/lib/python3.10/site-packages (from pipx) (23.2)
Requirement already satisfied: platformdirs>=2.1 in /tmp/_tool/Python/3.10.13/x64/lib/python3.10/site-packages (from pipx) (3.[11](https://github.com/digestaid/ai-classifier/actions/runs/7598094134/job/20693690876?pr=366#step:4:12).0)
Requirement already satisfied: tomli in /tmp/_tool/Python/3.10.13/x64/lib/python3.10/site-packages (from pipx) (2.0.1)
Collecting userpath!=1.9.0,>=1.6 (from pipx)
  Downloading userpath-1.9.1-py3-none-any.whl.metadata (3.0 kB)
Collecting click (from userpath!=1.9.0,>=1.6->pipx)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Downloading pipx-1.4.3-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.1/65.1 kB 3.6 MB/s eta 0:00:00
Downloading argcomplete-3.2.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 4.1 MB/s eta 0:00:00
Downloading userpath-1.9.1-py3-none-any.whl (9.1 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.2 MB/s eta 0:00:00
Installing collected packages: click, argcomplete, userpath, pipx
  WARNING: The script userpath is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pipx is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed argcomplete-3.2.1 click-8.1.7 pipx-1.4.3 userpath-1.9.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Notice:  A new release of pip is available: [23](https://github.com/digestaid/ai-classifier/actions/runs/7598094134/job/20693690876?pr=366#step:4:25).0.1 -> 23.3.2
Notice:  To update, run: pip install --upgrade pip
/tmp/_temp/9ce4d60b-ea35-4dc7-b344-c0[26](https://github.com/digestaid/ai-classifier/actions/runs/7598094134/job/20693690876?pr=366#step:4:28)0ba88c0f.sh: line 2: pipx: command not found
```

### PR DESCRIPTION
**Pull request by tiagovrtr**
Fixes #68 by explicitly calling `python3 -m pip install`

Signed-off-by: Tiago Reis <tiagovrtreis@gmail.com>

### CODE REVIEW

**Comment by tiagovrtr** [comment]
Any news @abatilo ?

**Review by abatilo — APPROVED** [review]
Sorry, somehow lost track of this. Looks good!

**Comment by abatilo** [comment]
@tiagovrtr Can you try pushing an empty commit? None of the CI was ever triggered

**Review by atkinsonm — APPROVED** [review]

**Comment by atkinsonm** [comment]
> @tiagovrtr Can you try pushing an empty commit? None of the CI was ever triggered

@abatilo since the source is a fork you may have to approve running the CI actions https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by j-adamczyk** [comment]
Could this be merged? This bug broke our CI pipelines at https://github.com/scikit-fingerprints/scikit-fingerprints, and currently to do a release ASAP we basically have to remove this action altogether.

**Comment by abatilo** [comment]
Apologies everyone for the delay here. Merging! I'll address 3.8 failures separately since 3.8 is EoL anyways

**Comment by rvgate** [comment]
Since this update my github actions have been failing, I was banging my head against the wall but the timing is too convenient;

```
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: 1.8.4
```

Screenshot 2024-10-28 020114

**Comment by abatilo** [comment]
@rvgate -- your failure appears to be from a step *after* this action ran. I'm not sure how much `actions-poetry` should be responsible for those steps,  but I'm open to your opinions.

**Comment by rvgate** [comment]
> @rvgate -- your failure appears to be from a step _after_ this action ran. I'm not sure how much `actions-poetry` should be responsible for those steps, but I'm open to your opinions.

There are no other steps defined, it runs within the actions-poetry step and has been introduced with this PR;

https://github.com/abatilo/actions-poetry/pull/71/commits/f0a4db5ec622e7785c1b05c656d810a9ddf014bc

**Comment by rvgate** [comment]
It could be related to the OS, in the tests I see that only ubuntu, windows and macos are actively monitored. My runner is running on Fedora.

**Comment by weskerfoot** [comment]
I have the same issue, using Ubuntu 22.04. The error is coming from `pipx install poetry==1.5.1`

**Pull request merged**
