### PR TITLE
feat: Add ability to install plugins as part of the action setup

### PR DESCRIPTION
**Pull request by xSAVIKx**
So starting somewhat time soon Poetry will not install plugins (such as export plugin e.g.) by default. So this PR add ability to install plugins by default and also installs the export plugin for you by default.

As part of the PR I have also updated versions of the GH actions used in workflows.

### CODE REVIEW

**Comment by xSAVIKx** [comment]
@abatilo can you please take a look? It'd be great to have this feature

**Comment by abatilo** [comment]
This seems reasonable to me!

**Review by abatilo — APPROVED** [review]

**Comment by xSAVIKx** [comment]
@abatilo, right, so plugin requires a particular version to be installed with a particular version of poetry. This means that we can have this feature, but let user decide if they want to install smth by default. At least that probably is a safer default strategy.

Can you please run the CI once again?

**Review by abatilo — APPROVED** [review]

**Comment by xSAVIKx** [comment]
@abatilo, sorry to bother but as I mentioned in the previous comment, while the Ubuntu has changed to v22.04 the required check you have right now will be never triggered and thus there's no way to proceed with merging the PR.

It would be great if you can reconfigure the check or force-merge the PR

**Comment by abatilo** [comment]
Sorry for the delay @xSAVIKx, I had gone on holiday. I'm happy with a force merge!

**Pull request merged**
