### PR TITLE
feat!: use pipx to isolate poetry

### PR DESCRIPTION
**Pull request by NargiT**
Following poetry recommendation, it better to use pipx instead of pip to avoid mixing application dependencies with poetry's 
https://python-poetry.org/docs/#ci-recommendations

BREAKING CHANGE: Switch using an isolated pipx virtualenv

### CODE REVIEW

**Review by lucsorel — APPROVED** [review]
I would also prefer poetry being installed with pipx for isolation sake. After using curl, it is the 2nd recommended way to install poetry (see https://python-poetry.org/docs/#installing-with-pipx).

Installing poetry using pip can cause dependency clashes with the project's dependencies if the project dependencies are not installed in a virtual environment.

**Comment by abatilo** [comment]
Thank you for the contribution @NargiT. I'm sorry that this got lost in my inbox. I like the spirit of the change but the changes break CI. Could you take a look?

**Review by lucsorel — APPROVED** [review]

**Review by lucsorel — APPROVED** [review]

**Review by lucsorel — APPROVED** [review]
Looks good to me (this time, I checked the checkboxes of the files to review)

**Review by lucsorel — APPROVED** [review]

**Comment by lucsorel** [comment]
hi @abatilo 

I reviewed the changes to this pull request but I don't understand why the process is still blocked :thinking: it looks like the CI must run but I don't understand how to trigger it.

**Comment by lucsorel** [comment]
@NargiT 

After a quick look, it seems that the CI does not work because [all tested versions of Poetry](https://github.com/NargiT/actions-poetry/blob/patch-1/.github/workflows/ci.yml) do not support the -U option that you use to install Poetry.

Either the obsolete versions of poetry should stop being supported (what is your advice, @abatilo?) or the github action must be tweaked to account for different major versions of poetry :shrug:

**Comment by abatilo** [comment]
@lucsorel Your approval doesn't do anything because you don't have write permissions to this repository.

I believe if @NargiT pushes a new commit to the branch then that should trigger the workflows again.

**Comment by abatilo** [comment]
@NargiT None of the required CI workflows have been triggered.

**Review by lucsorel — APPROVED** [review]

**Review by abatilo — APPROVED** [review]

**Comment by lucsorel** [comment]
thank you @abatilo for approving the PR, thank you @NargiT for proposing it :smiley:

**Comment by abatilo** [comment]
Sorry to all that it took so long to get this finally merged in.

**Pull request merged**
